### PR TITLE
prefabBufferGeometry support input bufferGeometry

### PR DESCRIPTION
**Pull request by eyworldwide**
We usually use `bufferGeometry` as a prefab, not a `geometry`. When using a loader (such as THREE.ObjectLoader or THREE.ObjLoader) to load a model data, we also get a `bufferGeometry`, not a `geometry`.  Although we can use `fromBufferGeometry` to convert a bufferGeometry to geometry, I think it's not a good practice because `fromBufferGeometry` is evil. (see: https://github.com/mrdoob/three.js/issues/6327) . I've tested in my project that `fromBufferGeometry` can occupy lots of memory (about 30% of whole app's memory, freak me out just a little).  Well, I add a third parameter (`isBufferGeometry`) to the `prefabBufferGeometry` constructor and retain the original logic of `geometry` as a prefab. But I think it's more efficient to use `bufferGeometry`.

### CODE REVIEW

**Comment by zadvorsky** [comment]
Hey. Thanks for looking into this, it's been on my todo list for a while.
Looks like you branched this off an older version (before I moved to ES6), so there are some conflicts. I'll try to merge this over the weekend.

**Comment by eyworldwide** [comment]
Nice! Looking forward to your merged code and thanks for your awesome work!

**Comment by zadvorsky** [comment]
I went ahead and manually merged your changes, so I'll close this PR.
I'm using THREE.BufferGeometry.isBufferGeometry to check for geometry type instead of adding a 3rd parameter to the constructor.
I also added support for indexed buffer geometries.

Changes are live on version 2.3.0

**Comment by eyworldwide** [comment]
Stupid Me! I forgot that Mrdoob has already assigned`isBufferGeometry` property to Geometries. Your code is better. Thanks @zadvorsky

**Pull request closed without merging**
